import assert from 'node:assert/strict';
import fs from 'node:fs';

const main = fs.readFileSync(new URL('../src/main.js', import.meta.url), 'utf8');
const pkg = JSON.parse(fs.readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const style = fs.readFileSync(new URL('../src/style.css', import.meta.url), 'utf8');
const backend = fs.readFileSync(new URL('../backend/app.py', import.meta.url), 'utf8');
const renderer = fs.readFileSync(new URL('../backend/render.py', import.meta.url), 'utf8');
const sync = fs.readFileSync(new URL('../src/sync.js', import.meta.url), 'utf8');
const index = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');

assert.ok(main.includes('/api/align'), 'AI precise endpoint missing');
assert.ok(main.includes('/api/render/start'), 'optimized async render endpoint missing');
assert.ok(main.includes('/status'), 'real render-progress polling missing');
assert.ok(main.includes('AI Precise'), 'AI mode UI missing');
assert.ok(main.includes('Split phrase after this word'), 'manual phrase splitting missing');
assert.ok(main.includes('Join with next phrase'), 'manual phrase joining missing');
assert.ok(main.includes("data-wm=\"image\""), 'image watermark UI missing');
assert.ok(main.includes("data-wm=\"video\""), 'video watermark UI missing');
assert.ok(style.includes('.timeline-viewport'), 'waveform editor styling missing');
assert.ok(main.includes('/api/backgrounds/discover'), 'online background discovery missing');
assert.ok(main.includes('refreshBackgrounds'), 'background refresh button missing');
assert.ok(main.includes('/api/backgrounds/fetch'), 'background fetch/proxy missing');
assert.ok(main.includes('Phrase translation'), 'manual phrase translation editor missing');
assert.ok(backend.includes('app.mount("/assets"'), 'assets route missing');

assert.equal(pkg.dependencies, undefined, 'frontend should have no runtime npm dependencies');
assert.ok(!main.includes('@ffmpeg/ffmpeg'), 'ffmpeg.wasm should not be used');
assert.ok(!main.includes("import './style.css'"), 'native browser module must not import CSS as JavaScript');
assert.ok(index.includes('rel="stylesheet" href="/src/style.css"'), 'stylesheet link missing from index.html');
assert.ok(backend.includes('quran_refine'), 'Qur’an acoustic refinement backend missing');
assert.ok(backend.includes('_letter_token_timings'), 'AI acoustic letter timing extraction missing');
assert.ok(backend.includes('"letterTimings": letter_tokens'), 'AI letter timings missing from alignment response');
assert.ok(backend.includes('ctc_blank_boundary_curve'), 'generic CTC blank boundary refinement missing');
assert.ok(sync.includes('alignSahihTokensToPhraseRanges'), 'phrase-level Saheeh matching missing');
assert.ok(backend.includes('StaticFiles'), 'Python backend should serve the frontend directly');
assert.ok(backend.includes('progress_callback'), 'FFmpeg progress callback missing');
assert.ok(backend.includes('/api/render/{job_id}/status'), 'render progress endpoint missing');
assert.ok(!fs.existsSync(new URL('../vite.config.js', import.meta.url)), 'Vite should not be required in v5');
console.log('Static UI/backend architecture checks passed.');

assert.ok(main.includes('Arabic word / letters'), 'manual Arabic display editor missing');
assert.ok(main.includes('settingsPlayPause'), 'settings preview playback controls missing');
assert.ok(main.includes('min="8" max="88" value="27"'), 'verse/surah block position control range not fixed');
assert.ok(main.includes("darkness: Number(clip.darkness ?? 0)"), 'zero darkness must be respected');
assert.ok(main.includes("autoDim: false"), 'new uploaded backgrounds should not auto-dim by default');
assert.ok(main.includes("fit: 'contain'"), 'new uploaded backgrounds should preserve the full frame by default');

assert.ok(main.includes('ayahEndSign'), 'numbered ayah end sign rendering missing');
assert.ok(main.includes('detect_repeats'), 'automatic repeated-ayah detection request missing');
assert.ok(main.includes('Repeats and going backwards are supported'), 'repeat-aware passage help missing');
assert.ok(main.includes('markSelectedBlockForDeletion'), 'single timeline-block deletion staging missing');
assert.ok(main.includes('recheckPendingBlockDeletions'), 'post-block-deletion AI re-check flow missing');
assert.ok(main.includes('ayahsWithoutPendingWordBlocks'), 'word-block deletion must preserve the rest of its ayah');
assert.ok(main.includes("$('basmalahMode').value = 'never'"), 'deleting Basmalah must prevent AI from adding it back');
assert.ok(main.includes('previous alignment was restored'), 'failed AI re-check must restore the previous successful alignment');
assert.ok(style.includes('.word-segment.pending-delete'), 'pending word-block deletion styling missing');
assert.ok(main.includes('buildLetterTimings'), 'automatic per-letter timing generation missing');
assert.ok(main.includes('adjustLetterBoundary'), 'manual letter-boundary editing missing');
assert.ok(main.includes('letterStartPlayhead') && main.includes('letterEndPlayhead'), 'playhead-based letter correction controls missing');
assert.ok(main.includes('activeLetterIndex'), 'letter-level canvas highlighting missing');
assert.ok(main.includes('const beforeText = graphemes.slice(0, letterIndex)'), 'connected Arabic letter clipping fix missing');
assert.ok(/if \(englishLines\.length\)[\s\S]{0,180}ctx\.textAlign = 'center'/.test(main), 'English subtitle centering reset missing');
assert.ok(main.includes('phraseOverlayBlob(group, word.wordIndex, unit.letterIndex)'), 'selected word/letter highlight export missing');
assert.ok(style.includes('.letter-timing-editor'), 'letter timing editor styling missing');

assert.ok(main.includes('leadingBasmalah'), 'frontend basmalah handling missing');
assert.ok(backend.includes('align_leading_basmalah'), 'safe post-alignment basmalah handling missing');
assert.ok(main.includes('basmalah_mode'), 'basmalah mode selector/request missing');
assert.ok(main.includes('Alignment safety check'), 'frontend alignment validation missing');
assert.ok(backend.includes('/api/backgrounds/discover'), 'backend background discovery endpoint missing');
assert.ok(backend.includes('Wikimedia Commons') || backend.includes('commons.wikimedia.org'), 'Wikimedia Commons source missing');

assert.ok(!/export function buildSemanticGroups[\s\S]{0,1800}usableTimings/.test(sync), 'buildSemanticGroups must not reference undefined timing variables');
assert.ok(!/export function buildWordGroups[\s\S]{0,1800}usableTimings/.test(sync), 'buildWordGroups must not reference undefined timing variables');

assert.ok(main.includes('Enable Intro Title Card'), 'intro toggle UI missing');
assert.ok(main.includes('introPreviewBtn'), 'intro preview control missing');
assert.ok(main.includes("form.append('intro_title'"), 'intro title upload missing');
assert.ok(main.includes("sound: intro.sound"), 'intro sound metadata missing');
assert.ok(backend.includes('intro_title'), 'intro title backend upload missing');
assert.ok(sync.includes('finalTimelineDuration'), 'intro-safe timeline helper missing');
assert.ok(main.includes('Shorts Retention Mode'), 'retention-mode UI missing');
assert.ok(main.includes('retentionPlan()'), 'phrase-safe retention planner missing');
assert.ok(main.includes('retentionHookBlob'), 'first-second hook overlay missing');
assert.ok(renderer.includes('audio_start_offset'), 'immediate-voice audio trim missing');
assert.ok(renderer.includes('zoompan='), 'frame-one background motion missing');
assert.ok(main.includes('highlightGranularity'), 'word/letter highlight selector missing');
assert.ok(main.includes('<option value="word" selected>'), 'word-by-word highlighting must be the default');
assert.ok(main.includes('phraseHighlightMode'), 'per-phrase highlight selector missing');
assert.ok(main.includes('highlightModeForGroup'), 'per-phrase highlight override resolver missing');
assert.ok(main.includes("groupHighlightMode === 'letter'"), 'preview/export must branch per phrase block');
assert.ok(main.includes('timedWordsForGroup'), 'word-highlight timing export missing');
assert.ok(main.includes('wordHighlightColor'), 'word-highlight color control missing');
assert.ok(main.includes('projectDashboard'), 'project dashboard UI missing');
assert.ok(main.includes('indexedDB.open(PROJECT_DB_NAME'), 'local project persistence missing');
assert.ok(main.includes('saveCurrentProject'), 'project save action missing');
assert.ok(main.includes('importPortableProject'), 'portable project import missing');
assert.ok(main.includes('downloadProject'), 'portable project export missing');
assert.ok(main.includes('backgroundClips: state.backgroundClips.map(serializableBackgroundClip)'), 'background media project persistence missing');
assert.ok(main.includes('Circular shadow overlay'), 'positionable shadow overlay UI missing');
assert.ok(main.includes('drawShadowOverlay(ctx, width, height)'), 'shadow overlay preview compositing missing');
assert.ok(main.includes("form.append('shadow_overlay'"), 'shadow overlay export upload missing');
assert.ok(main.includes('shadowFile: state.shadowOverlay.file'), 'shadow overlay project persistence missing');
assert.ok(backend.includes('shadow_overlay'), 'shadow overlay backend upload missing');
assert.ok(renderer.includes('metadata.get("shadowOverlay")'), 'shadow overlay FFmpeg metadata missing');
assert.ok(renderer.includes('[vshadow]'), 'shadow overlay FFmpeg compositing missing');

assert.ok(main.includes('Built-in recitation library'), 'recitation library source UI missing');
assert.ok(main.includes('libraryReciter'), 'reciter dropdown missing');
assert.ok(main.includes('libraryStart') && main.includes('libraryEnd'), 'ayah range number pickers missing');
assert.ok(main.includes('/api/library/recitation'), 'recitation library endpoint usage missing');
assert.ok(backend.includes('RECITATION_LIBRARY'), 'backend recitation catalog missing');
assert.ok(backend.includes('Alafasy_128kbps'), 'Mishary source missing');
assert.ok(backend.includes('khalefa_al_tunaiji_64kbps'), 'Khalifa source missing');
assert.ok(backend.includes('Yasser_Ad-Dussary_128kbps'), 'Yasser source missing');
